[project]
name = "poetry-to-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "poetry>=1.8.5",
    "toml>=0.10.2",
]
